
package ws;

import logbin.SQLAdmin;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RegisterService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:9191/register?wsdl")
public class RegisterService
    extends Service
{

    private final static URL REGISTERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ws.RegisterService.class.getName());

    static {
        URL url = null;
        String address = null;
        try {
            URL baseUrl;
            baseUrl = ws.RegisterService.class.getResource(".");
            address = SQLAdmin.getInstance().getSystemValue("lb_host");
            String newServerAddress="192.168.55.13";
            //String newServerAddress="localhost"; // my
            if (address == null||!newServerAddress.equalsIgnoreCase(address)) {
                address = newServerAddress;
                SQLAdmin.getInstance().setSystemValue("lb_host", address, true);
            }
            url = new URL(baseUrl, "http://" + address + ":9191/register?WSDL");// release
            //url = new URL(baseUrl, "http://localhost:9191/register?wsdl"); // my
        }
        catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '" + address + "', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REGISTERSERVICE_WSDL_LOCATION = url;
    }
    /*static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ws.RegisterService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9191/register?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9191/register?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REGISTERSERVICE_WSDL_LOCATION = url;
    } */

    public RegisterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegisterService() {
        super(REGISTERSERVICE_WSDL_LOCATION, new QName("http://ws/", "RegisterService"));
    }

    /**
     * 
     * @return
     *     returns Register
     */
    @WebEndpoint(name = "RegisterPort")
    public Register getRegisterPort() {
        return super.getPort(new QName("http://ws/", "RegisterPort"), Register.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Register
     */
    @WebEndpoint(name = "RegisterPort")
    public Register getRegisterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "RegisterPort"), Register.class, features);
    }

}
